Properly gather version information from git
gardenlinux/backup_package-build pull request #37
Opened 2023-12-01 08:10 UTC by alee-cd

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #29 #30 

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2023-12-01 08:50 UTC, nanory requested changes

2023-12-01 08:50 UTC, nanory commented on container/bin/build_source
> +get_upstream-version() (
We shouldn't mix cases here and stick to the so called snake case which means that the function name should look like this `get_upstream_version`.

2023-12-01 08:50 UTC, nanory commented on container/bin/build_source
> +		if [ -f debian/changelog ]; then
This is a wrong assumption here. It's not the existence of `debian/changelog` which decides if the version should be gathered from Git or if `dpkg-parsechangelog` could be used but it's the `source_type` which should decide that. 

Moreover, I wouldn't add this if statement to `get_version` but rather add it to `get_upstream_version` because why should `get_version` know when to call which function? `get_version` only wants to know what the upstream version of the upstream code is and it's then the responsibility of `get_upstream_version` to provide the proper version no matter if the source type is `git`, `debian` or `native`.

Therefore, this line should look like this:
```
local source_type=$1
...
commit_hash=$(git -C /input rev-parse HEAD)
package_version=$(get_upstream_version $source_type)
```

The `get_upstream_version` function would then decide based on the source_type:
```
get_upstream_version() (
    local source_type=$1

    if source_type == "git" ...
    elif source_type == "native" ...
    else ...
)
```

2023-12-01 08:50 UTC, nanory commented on container/bin/build_source
> +	package_version="${latest_tag}-0"
What purpose has this?

2023-12-01 08:55 UTC, alee-cd commented on container/bin/build_source
> +	package_version="${latest_tag}-0"
If latest_tag is 9.1, and then the package_version will become `9.1gardenlinux*` instead of `9.1-0gardenlinuix*`, and that may creates a problem if we want to switch to version directly from `Debian`.

2023-12-01 11:13 UTC, nanory requested changes

2023-12-01 11:13 UTC, nanory commented on container/bin/build_source
> +	package_version="${latest_tag}-0"
Ok I see. Maybe we should add some more explanation to this via comments so that it's clear why we add `-0` to it especially if we want to move to a Debian version in future if possible

2023-12-01 11:13 UTC, nanory commented on container/bin/build_source
> +	tag_suffix="$(yq -r '.jobs.build_pkg.with.tag_suffix // ""' < "$inputs_file")"
Can we rename this parameter to `git_filter`?
Its default should then be `.*`

2023-12-01 11:13 UTC, nanory commented on container/bin/build_source
> +	tag_mangle="$(yq -r '.jobs.build_pkg.with.tag_mangle // ""' < "$inputs_file")"
Can we rename this parameter to `git_tag_match`?
Its default should then be `(.*)`.

2023-12-01 11:13 UTC, nanory commented on container/bin/build_source
> +	if [ $tag_suffix ]; then
Could you remove this part here from line 183 to 193 and replace it with this?
```
get_latest_tag() (
  IFS='#' read -r url ref <<< "${source_git#git+}"
  echo $(git ls-remote --tags --refs $url | sed "s#.*\/##" | grep -E "$git_filter" | sed -E "s#$git_tag_match#\1#" | sort -V | tail -n1)
)

get_upstream_version() (
  ...
  latest_tag=$(get_latest_tag)
)
```

By doing this, you could define `git_filter` and `git_tag_match` like this:
* `git_filter`: `frr\-.*`
* `git_tag_match`: `frr\-([0-9\.]*).*`

The first group of `git_tag_match` is then always the designated version. It means then if we would have a tag schema like `v1.0.0`, you would simply define it like this:
* `git_filter`: `v.*`
* `git_tag_match`: `v([0-9\-]*)`

2023-12-01 16:18 UTC, nanory approved these changes
LGTM

2023-12-01 16:27 UTC, merged

2023-12-04 13:20 UTC, nkraetzschmar commented on container/apt/sources.list.d/gardenlinux.sources
this should never be needed! if we have dependecies on other self build packages these should always be explicit through the `dependencies` input of the `build_pkg.yml` or locally the `/pkgs` mount in the container. otherwise we would once again have the problem with needing an incrementally build repo