Decrease commands to reduce layers
gardenlinux/backup_package-build pull request #4
Opened 2023-10-27 13:01 UTC by alee-ntap

**What this PR does / why we need it**:

This PR is combining commands to decrease the amount of layers of the image. And added comment to make it easier to read.

**Which issue(s) this PR fixes**:
Fixes #1

2023-10-27 13:01 UTC, ghost commented
@alee-ntap Thank you for your contribution.

2023-10-30 08:25 UTC, Vincinator commented
note: before merging, we need to squash the `WIP` commits in main

2023-10-30 08:36 UTC, nanory commented
Hi @alee-ntap,
this looks already good but could you do the same also for `crossbuild.containerfile` so that it's streamlined?

2023-10-30 08:37 UTC, nanory requested changes

2023-10-30 08:37 UTC, nanory commented on build.containerfile
> +# Copy the build scripts to /usr/local/bin
Add a new line here

2023-10-30 08:43 UTC, alee-ntap commented
> Hi @alee-ntap, this looks already good but could you do the same also for `crossbuild.containerfile` so that it's streamlined?

Ok. Will do.

2023-10-31 13:43 UTC, nanory approved these changes
LGTM

2023-10-31 13:44 UTC, merged