Feature/5 replace pkg.ymal with workflow variables
gardenlinux/backup_package-build pull request #8
Opened 2023-11-07 14:02 UTC by alee-ntap

**What this PR does / why we need it**:

Use input variables of Github Action workflows with default values instead of provided veriables from pkg.yaml file.

**Which issue(s) this PR fixes**:
Fixes #5 

**Special notes for your reviewer**:
Due to it contains a changes on `build_source` script that needs to ship into the container. And container only gets published if merge into `main` branch. Currently cannot test to build `package-htop` against to the `WIP` branch. 

**Release note**:
Read version suffix from `git tag` and calling like an action module are not impelmented in this PR yet due to cannot test the changes on `build_source` script without an updated it inside the containers.

We better create separate issues for read version suffix from `git tag` and calling like an action module if needed.

2023-11-08 06:30 UTC, nanory requested changes
There are some changes, we should consider

2023-11-08 06:30 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
Are all of these env variables really needed during the build of the binary package? Are those env variables used in `build_indep` or `build_archdep` or could we skip setting them here?

2023-11-08 06:30 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e DEBIAN_SOURCE='${{ env.INPUT_DEBIAN_SOURCE }}' \
What purposes does `DEBIAN_SOURCE` have and how does it differ to `SOURCE_NAME`

2023-11-08 06:30 UTC, nanory commented on container/bin/build_source
> +	email="$EMAIL"
Why do we define two environment variables with the same value? Why not using `$EMAIL`, `$NAME` and all the other env variables that are passed to the container directly?

2023-11-08 06:30 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
We shouldn't split the version into `SOURCE_VERSION` and `VERSION_SUFFIX` but we should only pass one version to the container and its build script should do the splitting if needed. This way, we can directly pass the git tag to the corresponding Github Action workflow without splitting it beforehand. It's then easier for other package repos (e.g. package-htop) to just pass their Git Tag to `package-build`

2023-11-08 08:52 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
These were implemented in `build_source` script inside the container by purposes. You may find the script now at `container/bin/build_source` in this branch. We probably need to discuss with Nikolas if we want to remove them.
And I think these are not required but may provide as inputs options for other packages to call.

2023-11-08 08:52 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e DEBIAN_SOURCE='${{ env.INPUT_DEBIAN_SOURCE }}' \
These were implemented in `build_source` script inside the container by purposes. It seems different for me.

2023-11-08 08:53 UTC, alee-ntap commented on container/bin/build_source
> +	email="$EMAIL"
Good point. Will update that.

2023-11-08 09:04 UTC, alee-ntap commented on container/bin/build_source
> +	email="$EMAIL"
Not only $EMAIL and $NAME. I also directly use $DIST and $MESSAGE.

2023-11-08 09:06 UTC, alee-ntap commented on container/bin/build_source
> +	email="$EMAIL"
https://github.com/gardenlinux/package-build/pull/8/commits/ac28e26cb78d09a4a03600bc7dcfc15b1b7e1e0d

2023-11-08 09:08 UTC, alee-ntap commented on container/bin/build_source
> +	email="$EMAIL"
Hum, these makes me thinking of directly pass environment variables as $DEBEMAIL and $DEBFULLNAME to the `podman run`.

2023-11-08 09:14 UTC, alee-ntap commented on container/bin/build_source
> +	email="$EMAIL"
Done in: https://github.com/gardenlinux/package-build/pull/8/commits/8f028283cd32694b1bc7c8f6fb00e61c946997cf

2023-11-08 09:15 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
Right. Let me check how we have done that in the gitlab pipeline and see if we can use the same way to define and split that.

2023-11-08 09:50 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
I found current design in `build-package` is very difficult to test `build-pkg.yml` for other packages, eg: `build-htop`. Due to we needs to update the `build_source` script inside the container as well each time.
I created #9 for this. Let's land this PR so that I can test changes works for other package build eg: `package-htop`.

2023-11-09 01:06 UTC, nanory requested changes
There are still some open points before we can merge this change to `main`.

2023-11-09 01:06 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e DEBIAN_SOURCE='${{ env.INPUT_DEBIAN_SOURCE }}' \
Ok, I checked the code and I understand the purpose of `DEBIAN_SOURCE` now but I think we don't need this parameter. This parameter basically tells the build container and the centralized package pipeline, that the corresponding package repo (e.g. package-build) contains its own `debian/`directory and that this `debian/` directory should replace the `debian/` directory coming from the original sources. 

However, if we compare this functionality with the Gitlab pipeline, I asking myself why should we define such a paramter. Why not simply checking if the package repo contains a `debian/` directory and then simply replace the original one instead of defining an additional parameter for it.

Instead of checking the `pkg.yml` in the package repo's directory or checking if such a Github Action parameter is defined, the `build_source` script could easily check if this directory exists in the package repo's root directory. 

My main goal is to reduce the Github Action parameters and use as less parameters as possible. I don't see a use case where one would define  `debian/` directory but don't want to replace the origianl one by skiping this parameter, so we could use this fact and implement it accordingly.

2023-11-09 01:06 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
Ok, these parameters are needed in `build_source` but not in `build_indep` or `build_archdep` that is called by this specific job or am I wrong? 

If so, we could remove them here because as far as I can see, they are only needed by `build_source´ in the `source´ job instead of `build_indep` or `build_archdep` in the `package` job, no?

2023-11-09 01:06 UTC, nanory commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
I'm not sure if we should go like this and merge this already or find a solution to overcome this because we need a possibility to test changes in `package-build` (even in the pacakge build container) before we merge stuff to main.

I've send you a proposal of how we could achieve this. Could you have a look?

2023-11-09 13:13 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
You are right. I will drop these for `build_indep` and `build_archdep`.

2023-11-09 13:23 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e VERSION_SUFFIX='${{ env.INPUT_VERSION_SUFFIX }}' \
I found another way to test changes in `package-build`. Use bind mount `container/bin/` instead of `COPY`:
https://github.com/gardenlinux/package-build/pull/8/commits/37ca796ffc407bf8825b89e87b4a7f64e9c3666e
And really checkout the branch which triggered the workflow:
https://github.com/gardenlinux/package-build/pull/8/commits/ebb9d8eb19613a2ea261253266c8bff494b4c041

2023-11-10 15:08 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               -e DEBIAN_SOURCE='${{ env.INPUT_DEBIAN_SOURCE }}' \
Resolved: https://github.com/gardenlinux/package-build/issues/10

2023-11-13 11:04 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +          ref: ${{ github.ref_name }}
This line should be removed before we merge this PR
It is a clever workaround to test this PR, but it is unrelated to the goal of this PR. 

If we need the feature to be able to run from a branch, we should think about security settings. 
Would like to postpone this discussion and just remove this line before we merge this PR.

2023-11-13 11:04 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
Why do we need to bind mount the container/bin from the github action path, and not include it during the image build in the container? 

It looks like a potential source for incompatibility issues between the container/bin and the build_source container.

2023-11-13 11:04 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/,dst=/usr/local/sbin,ro" \
same as other comment above

2023-11-13 11:04 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +      build_options:
Hm, I understand the rational for this PR, but I do not concur with throwing away the `pkg.yaml` approach.

It does make sense to define default variables, if no `pkg.yaml` is specified, then the CI can take those variables. If the `pkg.yaml` exists, it should overwrite the defaults. 

This overwrite makes sense for cases where we have package specific variables, like `DEB_BUILD_OPTIONS` and  `DEB_BUILD_PROFILES`. Package specific parameters we need to include in version control of the package repo.  

Current implementation of package build is, that if `build_options` field is present in pkg.yaml, then it is added to the `DEB_BUILD_OPTIONS`. 

See line below:
```
DEB_BUILD_OPTIONS="terse $(yq -r '.build_options // ""' < "/input/pkg.yaml")"
```

We need the same for  `DEB_BUILD_PROFILES`. 


What this PR could do, is define default values for all variables:
- if no pkg.yaml is present? Every variable uses default value
- if pkg.yaml is partly present, pkg.yaml misses a few variables? Default values for only the missing variables are used
- if pkg.yaml is complete, all variables are defined? All pkg.yaml variables are used, no default value is taken.

2023-11-13 11:04 UTC, Vincinator commented on container/bin/build_source
> +	if [ -d /input/debian ]; then
Changes to the debian folder should only be done via Garden Linux patches

2023-11-13 11:04 UTC, Vincinator commented on container/bin/build_source
> +        if [ -d /input/debian ]; then
Changes to the debian folder should only be done via Garden Linux patches

2023-11-13 12:01 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
The reason is that we don't want to rebuild the container images every time when there is a small update or change in the `build_*` scripts. By using this `bind mount` path, we can always ensure that we have the `correct version` of the `build_*` scripts from the `same branch` we are running the `build_pkg.yml` workflow. This allows us to test the `build_pkg.yml` workflow and the `build_*` scripts during `development`.

2023-11-13 12:02 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/,dst=/usr/local/sbin,ro" \
Answered by the reason above. :)

2023-11-13 12:14 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +      build_options:
This proposed PR  is to combine the variables from the `pkg.yaml` file into the `build.yml` file using input variables. This will allow us to use a single YAML file instead of having two separate YAML files. Once we have identified the required `inputs`, I will update the `README.md` file to define the types of `input variables` that can be utilized in the `build.yml` file. These `variables` can be `supplied by other packages` to execute the `build_pkg.yml` workflows within the `build-package` project. If a variable is `not specified`, its `defaults value` will be used.

2023-11-13 12:35 UTC, alee-ntap commented on container/bin/build_source
> +	if [ -d /input/debian ]; then
In our current GitLab pipeline, we utilize the `patches` directory to possibility apply updates to both the `debian/` folder and the upstream source tree. An example of this can be found at: https://gitlab.com/gardenlinux/gardenlinux-package-cloud-init.

However, there is a variation in the pipeline when we provide separate `patches/` and `debian/` folders, as demonstrated in the following GitLab pipeline: https://gitlab.com/gardenlinux/gardenlinux-package-aws-kms-pkcs11. In this case, the GitLab pipeline uses the provided patches from `patches/` folder to update the upstream source tree. The `rsync` method is only triggered if the provided `debian/` folder exists.

Additionally, to avoid any race conditions, the patches are `only` applied from the `patches/` folder rather than the `debian/patches` folder.

I think it's a very clever design, so that I have replicated it here. :)

2023-11-13 12:35 UTC, alee-ntap commented on container/bin/build_source
> +        if [ -d /input/debian ]; then
Answered by the reason above. :)

2023-11-13 12:40 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +          ref: ${{ github.ref_name }}
You are correct. I have removed this line in the current pull request.

2023-11-13 13:28 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +      build_options:
Ok, I see - thanks for clarifying. 

Do I understand the PR correctly:
The variables are moved from a yaml configuration file, to a GitHub CI specific yaml file. Building a package locally would require the user to either look up the correct variables and specify the variables manually, or utilise some tool that can run github actions locally (e.g. https://github.com/nektos/act). 

Requirement for this change is to reduce redundant variable definitions, right? This PR would achieve this at the cost of additional steps required for local package builds. I am not sure if this is a reasonable trade-off. Are there other reasons?

2023-11-13 13:29 UTC, Vincinator commented on container/bin/build_source
> +	if [ -d /input/debian ]; then
Ok, works for now - fine with me. Should not be a blocker :)

2023-11-13 13:31 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
Could you please document this? 

It sounds reasonable to me during the bootstrapping of the package build. Would need to revisit this decision before we go live

Works for this PR 👍🏻

2023-11-13 13:42 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +      build_options:
May I know how the local package build method with `pkg.yaml` works? Maybe I should try it and see if anything we can improve from current local build method or utilise some tool that can run github actions locally (e.g. https://github.com/nektos/act). Hopefully there is something can do it better.

2023-11-13 14:26 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
Certainly. Allow me to explain the situation first, and then we can determine the best location for this document.

The `build_pkg.yml` file serves as a `reusable workflow` that `other packages` can utilize. When modifications are made to the `build_pkg.yml` workflow, it often requires corresponding changes in the `build_*` scripts to handle the input variables or something else. Consequently, the `git branch` in `build-package` project should include changes to both the `build_pkg.yml` and `build_*` scripts together.

Without bind-mounting the `build_*` scripts inside the container, we would be unable to effectively test the `build_pkg.yml` workflow if the corresponding changes to the `build_*` scripts in the same branch are not present inside the container.

In addition to the specific utilize of the `build_pkg.yml` workflow from a particular branch using `@workflow-branch-name`, as demonstrated in this example: https://github.com/gardenlinux/package-htop/actions/runs/6823007358/workflow
There is an additional aspect to consider. When the `actions/checkout` action is used with `repository:` but without the `ref:`, it checkouts the `default branch` of the repository. Therefore, it is necessary to explicitly specify the `ref:` option with the `workflow-branch-name` that specific utilize from other packages along with the `repository`, as shown below:

```
      - uses: actions/checkout@v4
        with:
          repository: gardenlinux/package-build
          ref: workflow-branch-name
```

This explains the presence of the `ref: ${{ github.ref_name }}` line in the previous version of this PR. I believe it won't harm to the workflow to cause any issues if the workflow is utilized by other packages in the default branch, as the variable will also be changed to the default branch. 
(However, it's a workaround for testing purposes. I dropped it due to it's unrelated to the goal of this PR. Please let me know if we do need it or just to be needed in this document.)

Now, let's discuss the most appropriate placement and title for this document. :)

2023-11-13 15:10 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +      build_options:
Local package builds are not documented yet. I haven't tested local builds yet, @nkraetzschmar is working on it - I think he has a setup.

2023-11-13 15:15 UTC, Vincinator commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
Thanks for explaining! 
I think you could create an issue explaining this, so we have a reminder to re-iterate on this before the "go-live". 
I'm also fine with a markdown file in a doc/ folder. How you prefer.

2023-11-13 15:22 UTC, alee-ntap commented on .github/workflows/build_pkg.yml
> +               --mount="type=bind,src=$PWD/${GITHUB_ACTION_PATH}/container/bin,dst=/usr/local/sbin,ro" \
Okay. Let me create an issue. I am thinking of place it in the `.github/workflows/` with explain for the two different yml files for. And how to utilize this `build_pkg.yml` from other packages.

2023-11-21 14:00 UTC, nanory commented
As discussed internally, we won't remove the `pkg.yml` but still we will re-use some of the changes mentioned here. For this reason, the following follup-up issues have been created:
* #14 
* #15 
* #17

2023-11-21 14:00 UTC, closed without merging